
import java.text.MessageFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author MICY
 */
public class POS extends javax.swing.JFrame {

    /**
     * Creates new form POS
     */
    public POS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jbtn7 = new javax.swing.JButton();
        jbtn8 = new javax.swing.JButton();
        jbtn4 = new javax.swing.JButton();
        jbtn5 = new javax.swing.JButton();
        jbtn6 = new javax.swing.JButton();
        jbtn1 = new javax.swing.JButton();
        jbtn2 = new javax.swing.JButton();
        jbtn3 = new javax.swing.JButton();
        jbtn0 = new javax.swing.JButton();
        jbtnDot = new javax.swing.JButton();
        jbtnC = new javax.swing.JButton();
        jbtn9 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jbtnConverse = new javax.swing.JButton();
        jbtnDunk = new javax.swing.JButton();
        jbtnConverseLow = new javax.swing.JButton();
        jbtnAirforce1 = new javax.swing.JButton();
        jbtnCampus = new javax.swing.JButton();
        jbtnGucci = new javax.swing.JButton();
        jbtnjm = new javax.swing.JButton();
        jbtnNb480 = new javax.swing.JButton();
        jbtnNb530 = new javax.swing.JButton();
        jbtnOnitsuka = new javax.swing.JButton();
        jbtnOxford = new javax.swing.JButton();
        jbtnplayboy = new javax.swing.JButton();
        jbtnSamba = new javax.swing.JButton();
        jbtnTravis = new javax.swing.JButton();
        jbtnVans = new javax.swing.JButton();
        jbtnWhite = new javax.swing.JButton();
        jbtnysl = new javax.swing.JButton();
        jbtnzara = new javax.swing.JButton();
        jbtnpuma = new javax.swing.JButton();
        jbtnChunky = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtTotal = new javax.swing.JTextField();
        jtxtSubtotal = new javax.swing.JTextField();
        jtxtTax = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtxtChange = new javax.swing.JTextField();
        jtxtDisplay = new javax.swing.JTextField();
        jcboPayment = new javax.swing.JComboBox<>();
        jPanel8 = new javax.swing.JPanel();
        jbtnRemove = new javax.swing.JButton();
        jbtnPay = new javax.swing.JButton();
        jbtnPrint = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jtxtBarcode = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtn7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtn7.setText("7");
        jbtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn7ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 80, 100));

        jbtn8.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtn8.setText("8");
        jbtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn8ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 80, 100));

        jbtn4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtn4.setText("4");
        jbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn4ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 80, 100));

        jbtn5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtn5.setText("5");
        jbtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn5ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 80, 100));

        jbtn6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtn6.setText("6");
        jbtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn6ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 80, 100));

        jbtn1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtn1.setText("1");
        jbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 80, 100));

        jbtn2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtn2.setText("2");
        jbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn2ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 80, 100));

        jbtn3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtn3.setText("3");
        jbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn3ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 80, 100));

        jbtn0.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtn0.setText("0");
        jbtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn0ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 80, 100));

        jbtnDot.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnDot.setText(".");
        jbtnDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDotActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnDot, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 80, 100));

        jbtnC.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnC.setText("C");
        jbtnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnC, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 80, 100));

        jbtn9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtn9.setText("9");
        jbtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn9ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 80, 100));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 300, 460));

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnConverse.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnConverse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/converse.jpg"))); // NOI18N
        jbtnConverse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnConverseActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnConverse, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, 110, 90));

        jbtnDunk.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnDunk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/nikeDunkhigh (1).jpg"))); // NOI18N
        jbtnDunk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDunkActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnDunk, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 110, 90));

        jbtnConverseLow.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnConverseLow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/converselow1 (1).jpg"))); // NOI18N
        jbtnConverseLow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnConverseLowActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnConverseLow, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 110, 90));

        jbtnAirforce1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnAirforce1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/airforce1.jpg"))); // NOI18N
        jbtnAirforce1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAirforce1ActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnAirforce1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 110, 90));

        jbtnCampus.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnCampus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/campus.jpg"))); // NOI18N
        jbtnCampus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCampusActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnCampus, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 110, 90));

        jbtnGucci.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnGucci.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/gloafers.jpg"))); // NOI18N
        jbtnGucci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGucciActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnGucci, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 110, 90));

        jbtnjm.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnjm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/jm.jpg"))); // NOI18N
        jbtnjm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnjmActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnjm, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 110, 90));

        jbtnNb480.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnNb480.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/nb480.jpg"))); // NOI18N
        jbtnNb480.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNb480ActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnNb480, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 110, 90));

        jbtnNb530.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnNb530.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/nb530.jpg"))); // NOI18N
        jbtnNb530.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNb530ActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnNb530, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 110, 90));

        jbtnOnitsuka.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnOnitsuka.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/onitsuka.jpg"))); // NOI18N
        jbtnOnitsuka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnOnitsukaActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnOnitsuka, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, 110, 90));

        jbtnOxford.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnOxford.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/oxford (1).jpg"))); // NOI18N
        jbtnOxford.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnOxfordActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnOxford, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 110, 90));

        jbtnplayboy.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnplayboy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/playboy (1).jpg"))); // NOI18N
        jbtnplayboy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnplayboyActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnplayboy, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 110, 90));

        jbtnSamba.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnSamba.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/samba.jpg"))); // NOI18N
        jbtnSamba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSambaActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnSamba, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 110, 90));

        jbtnTravis.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnTravis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/travisLOW.jpg"))); // NOI18N
        jbtnTravis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTravisActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnTravis, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 110, 90));

        jbtnVans.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnVans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/vans.jpg"))); // NOI18N
        jbtnVans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnVansActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnVans, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, 110, 90));

        jbtnWhite.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnWhite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/white.jpg"))); // NOI18N
        jbtnWhite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnWhiteActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnWhite, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 110, 90));

        jbtnysl.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnysl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/ysl.jpg"))); // NOI18N
        jbtnysl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnyslActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnysl, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 110, 90));

        jbtnzara.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnzara.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/zara.jpg"))); // NOI18N
        jbtnzara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnzaraActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnzara, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, 110, 90));

        jbtnpuma.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnpuma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/puma (1).jpg"))); // NOI18N
        jbtnpuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnpumaActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnpuma, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, 110, 90));

        jbtnChunky.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnChunky.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/chunky (1).jpg"))); // NOI18N
        jbtnChunky.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnChunkyActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnChunky, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 350, 110, 90));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 30, 660, 460));

        jTable1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Quantity", "Amount"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 330, 390));

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 1320, 170));

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Total");
        jPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("SubTotal");
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Tax");
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jtxtTotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTotalActionPerformed(evt);
            }
        });
        jPanel6.add(jtxtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 210, -1));

        jtxtSubtotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtSubtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtSubtotalActionPerformed(evt);
            }
        });
        jPanel6.add(jtxtSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 210, -1));

        jtxtTax.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTaxActionPerformed(evt);
            }
        });
        jPanel6.add(jtxtTax, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 210, -1));

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 400, 160));

        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setText("Payment Method");
        jPanel7.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setText("Change");
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setText("Cash");
        jPanel7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jtxtChange.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtChangeActionPerformed(evt);
            }
        });
        jPanel7.add(jtxtChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 190, -1));

        jtxtDisplay.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDisplayActionPerformed(evt);
            }
        });
        jPanel7.add(jtxtDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 190, -1));

        jcboPayment.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jcboPayment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Visa Card", "Master Card" }));
        jcboPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboPaymentActionPerformed(evt);
            }
        });
        jPanel7.add(jcboPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 190, 40));

        jPanel4.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, 420, 160));

        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnRemove.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnRemove.setText("Remove");
        jbtnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRemoveActionPerformed(evt);
            }
        });
        jPanel8.add(jbtnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 190, 40));

        jbtnPay.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnPay.setText("Pay");
        jbtnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPayActionPerformed(evt);
            }
        });
        jPanel8.add(jbtnPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 190, 40));

        jbtnPrint.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnPrint.setText("Print");
        jbtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPrintActionPerformed(evt);
            }
        });
        jPanel8.add(jbtnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 190, 40));

        jbtnExit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnExit.setText("Exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });
        jPanel8.add(jbtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 280, 40));

        jbtnReset.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });
        jPanel8.add(jbtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 190, 40));

        jPanel4.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 40, 430, 160));

        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel9.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 1320, 170));

        jPanel11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setText("Total");
        jPanel11.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setText("SubTotal");
        jPanel11.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setText("Tax");
        jPanel11.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextField4.setText("jTextField1");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel11.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 210, -1));

        jTextField5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextField5.setText("jTextField1");
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel11.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 210, -1));

        jTextField6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextField6.setText("jTextField1");
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jPanel11.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 210, -1));

        jPanel9.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 400, 160));

        jPanel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setText("SubTotal");
        jPanel12.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel14.setText("Total");
        jPanel12.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel15.setText("Tax");
        jPanel12.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jPanel9.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, 420, 160));

        jPanel13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel9.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 40, 430, 160));

        jPanel4.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 1320, 270));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 1320, 270));

        jtxtBarcode.setFont(new java.awt.Font("barcode font", 1, 48)); // NOI18N
        jtxtBarcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtBarcodeActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtBarcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 420, 330, 70));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
   //=============FUNCTION==================================
    public void ItemCost()
    {
       double sum = 0;
       for (int i = 0; i < jTable1.getRowCount(); i++)
       {
           sum = sum + Double.parseDouble(jTable1.getValueAt(i, 2).toString());
       }
       jtxtSubtotal.setText(Double.toString(sum));
       double cTotal1 = Double.parseDouble(jtxtSubtotal.getText());
       double cTax = (cTotal1  * 12)/100;
       String iTaxTotal = String.format("₱ %.2f", cTax);
       jtxtTax.setText(iTaxTotal);
       String iSubTotal = String.format("₱ %.2f", cTotal1);
       jtxtSubtotal.setText(iSubTotal);
       String iTotal = String.format("₱ %.2f", cTotal1 + cTax);
       jtxtTotal.setText(iTotal);
       String Barcode = String.format("Total is %.2f", cTotal1 + cTax);
       jtxtBarcode.setText(Barcode);    
    }
    
      //===============================FUNCTION Change=====================
    public void Change()
    {
       double sum = 0;
       double tax = 3.9;
       double cash = Double.parseDouble(jtxtDisplay.getText());
        for (int i = 0; i < jTable1.getRowCount(); i++)
       {
           sum = sum + Double.parseDouble(jTable1.getValueAt(i, 2).toString());
       }
        double cTax = (sum * 12)/100;
        double cChange = (cash - (sum + cTax));
        String ChangeGiven = String.format("₱ %.2f",cChange);
        jtxtChange.setText(ChangeGiven);     
    }
    
    private void jbtnConverseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnConverseActionPerformed
        // TODO add your handling code here:
        double PriceOfItem = 780;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Converse Chuck Taylor", "1",PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnConverseActionPerformed

    private void jbtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn7ActionPerformed
     
        String Enternumber = jtxtDisplay.getText();
        if (Enternumber == "")
        {
            jtxtDisplay.setText(jbtn7.getText());
        }
        else
        {
            Enternumber = jtxtDisplay.getText() + jbtn7.getText();
            jtxtDisplay.setText(Enternumber); 
        }
    }//GEN-LAST:event_jbtn7ActionPerformed

    private void jbtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn8ActionPerformed
        
          String Enternumber = jtxtDisplay.getText();
        if (Enternumber == "")
        {
            jtxtDisplay.setText(jbtn8.getText());
        }
        else
        {
            Enternumber = jtxtDisplay.getText() + jbtn8.getText();
            jtxtDisplay.setText(Enternumber); 
        }
    }//GEN-LAST:event_jbtn8ActionPerformed

    private void jbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn4ActionPerformed
        
        String Enternumber = jtxtDisplay.getText();
        if (Enternumber == "")
        {
            jtxtDisplay.setText(jbtn4.getText());
        }
        else
        {
            Enternumber = jtxtDisplay.getText() + jbtn4.getText();
            jtxtDisplay.setText(Enternumber); 
        }
    }//GEN-LAST:event_jbtn4ActionPerformed

    private void jbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn5ActionPerformed
        
         String Enternumber = jtxtDisplay.getText();
        if (Enternumber == "")
        {
            jtxtDisplay.setText(jbtn5.getText());
        }
        else
        {
            Enternumber = jtxtDisplay.getText() + jbtn5.getText();
            jtxtDisplay.setText(Enternumber); 
        }
    }//GEN-LAST:event_jbtn5ActionPerformed

    private void jbtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn6ActionPerformed
        
         String Enternumber = jtxtDisplay.getText();
        if (Enternumber == "")
        {
            jtxtDisplay.setText(jbtn6.getText());
        }
        else
        {
            Enternumber = jtxtDisplay.getText() + jbtn6.getText();
            jtxtDisplay.setText(Enternumber); 
        }
    }//GEN-LAST:event_jbtn6ActionPerformed

    private void jbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn1ActionPerformed
        
           String Enternumber = jtxtDisplay.getText();
        if (Enternumber == "")
        {
            jtxtDisplay.setText(jbtn1.getText());
        }
        else
        {
            Enternumber = jtxtDisplay.getText() + jbtn1.getText();
            jtxtDisplay.setText(Enternumber); 
        }
    }//GEN-LAST:event_jbtn1ActionPerformed

    private void jbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn2ActionPerformed
        
        String Enternumber = jtxtDisplay.getText();
        if (Enternumber == "")
        {
            jtxtDisplay.setText(jbtn2.getText());
        }
        else
        {
            Enternumber = jtxtDisplay.getText() + jbtn2.getText();
            jtxtDisplay.setText(Enternumber); 
        }
    }//GEN-LAST:event_jbtn2ActionPerformed

    private void jbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn3ActionPerformed
       
           String Enternumber = jtxtDisplay.getText();
        if (Enternumber == "")
        {
            jtxtDisplay.setText(jbtn3.getText());
        }
        else
        {
            Enternumber = jtxtDisplay.getText() + jbtn3.getText();
            jtxtDisplay.setText(Enternumber); 
        }
    }//GEN-LAST:event_jbtn3ActionPerformed

    private void jbtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn0ActionPerformed
        
         String Enternumber = jtxtDisplay.getText();
        if (Enternumber == "")
        {
            jtxtDisplay.setText(jbtn0.getText());
        }
        else
        {
            Enternumber = jtxtDisplay.getText() + jbtn0.getText();
            jtxtDisplay.setText(Enternumber); 
        }
    }//GEN-LAST:event_jbtn0ActionPerformed

    private void jbtnDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDotActionPerformed
        
        if (! jtxtDisplay.getText().contains("."))
        {
            jtxtDisplay.setText(jtxtDisplay.getText() + jbtnDot.getText());
        }
        
    }//GEN-LAST:event_jbtnDotActionPerformed

    private void jbtnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCActionPerformed
        
        jtxtDisplay.setText("");
        jtxtChange.setText("");
        
    }//GEN-LAST:event_jbtnCActionPerformed

    private void jbtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn9ActionPerformed
     
       String Enternumber = jtxtDisplay.getText();
        if (Enternumber == "")
        {
            jtxtDisplay.setText(jbtn9.getText());
        }
        else
        {
            Enternumber = jtxtDisplay.getText() + jbtn9.getText();
            jtxtDisplay.setText(Enternumber); 
        }
    }//GEN-LAST:event_jbtn9ActionPerformed

    private void jbtnDunkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDunkActionPerformed
        
        double PriceOfItem = 880;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Nike Air jordan Dunk", "1",PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnDunkActionPerformed

    private void jbtnConverseLowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnConverseLowActionPerformed
        
        double PriceOfItem = 570;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Converse Low Chuck Taylor ", "1",PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnConverseLowActionPerformed

    private void jbtnAirforce1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAirforce1ActionPerformed
       
        double PriceOfItem = 550;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Nike Airforce 1 ", "1",PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnAirforce1ActionPerformed

    private void jbtnCampusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCampusActionPerformed
       
        double PriceOfItem = 1290;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Adidas Campus Black", "1",PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnCampusActionPerformed

    private void jbtnGucciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGucciActionPerformed
        
        double PriceOfItem = 7480;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Gucci Loafers", "1",PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnGucciActionPerformed

    private void jbtnjmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnjmActionPerformed
        
        double PriceOfItem = 980;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Black Shoes", "1",PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnjmActionPerformed

    private void jbtnNb480ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNb480ActionPerformed
        
        double PriceOfItem = 1380;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"New Balance 480", "1",PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnNb480ActionPerformed

    private void jbtnNb530ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNb530ActionPerformed
       
        double PriceOfItem = 1320;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"New Balance 530", "1",PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnNb530ActionPerformed

    private void jbtnOnitsukaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnOnitsukaActionPerformed
       
        double PriceOfItem = 1780;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Adidas Onitsuka Tiger", "1",PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnOnitsukaActionPerformed

    private void jbtnOxfordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnOxfordActionPerformed
       double PriceOfItem = 3480;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Oxford Black Shoes", "1",PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnOxfordActionPerformed

    private void jbtnplayboyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnplayboyActionPerformed
       double PriceOfItem = 2980;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Playboy Wet Look Black Shoes", "1",PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnplayboyActionPerformed

    private void jbtnSambaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSambaActionPerformed
       double PriceOfItem = 2580;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Adidas Samba", "1",PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnSambaActionPerformed

    private void jbtnTravisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTravisActionPerformed
        double PriceOfItem = 3780;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Nike Dunk Travis ", "1",PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnTravisActionPerformed

    private void jbtnVansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnVansActionPerformed
       double PriceOfItem = 780;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Vans Old Skool", "1",PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnVansActionPerformed

    private void jbtnWhiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnWhiteActionPerformed
       double PriceOfItem = 780;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Converse Chuck Taylor", "1",PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnWhiteActionPerformed

    private void jbtnyslActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnyslActionPerformed
       double PriceOfItem = 8580;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Saint Laurent Loafers", "1",PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnyslActionPerformed

    private void jbtnzaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnzaraActionPerformed
        double PriceOfItem = 7880;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Zara Black Shoes", "1",PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnzaraActionPerformed

    private void jbtnpumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnpumaActionPerformed
       double PriceOfItem = 5780;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Puma Palermo", "1",PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnpumaActionPerformed

    private void jbtnChunkyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnChunkyActionPerformed
       double PriceOfItem = 3780;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Nike Al8", "1",PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnChunkyActionPerformed

    private void jtxtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTotalActionPerformed

    private void jtxtSubtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtSubtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSubtotalActionPerformed

    private void jtxtTaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTaxActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jtxtDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDisplayActionPerformed

    private void jtxtChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtChangeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtChangeActionPerformed

    private void jcboPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboPaymentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcboPaymentActionPerformed

    private void jtxtBarcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtBarcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtBarcodeActionPerformed

    private void jbtnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPayActionPerformed
       if (jcboPayment.getSelectedItem().equals("Cash")) 
       {
           Change();
       }
       else
       {
           jtxtChange.setText("");
           jtxtDisplay.setText("");
       }
    }//GEN-LAST:event_jbtnPayActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        jtxtChange.setText("");
        jtxtTax.setText("");
        jtxtTotal.setText("");
        jtxtSubtotal.setText("");
        jtxtDisplay.setText("");
        jtxtBarcode.setText("");
       
        
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jbtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPrintActionPerformed
        
        MessageFormat header = new MessageFormat("Printing in progress");
        MessageFormat footer = new MessageFormat("Page {0, number, integer }");
        
        try
        {
            jTable1.print(JTable.PrintMode.NORMAL,header,footer);
        }
        catch(java.awt.print.PrinterException e)
        {
            System.err.format("No Printer found", e.getMessage());
        }
        
    }//GEN-LAST:event_jbtnPrintActionPerformed

    private void jbtnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRemoveActionPerformed
         DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
         int RemoveItem = jTable1.getSelectedRow();
         if(RemoveItem >= 0)
         {
             model.removeRow(RemoveItem);
         }
         ItemCost();
         if (jcboPayment.getSelectedItem().equals("Cash"))
         {
             Change();
         }
         else
         {
             jtxtChange.setText("");
             jtxtDisplay.setText("");
         }
    }//GEN-LAST:event_jbtnRemoveActionPerformed
    
    private JFrame frame;
    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        frame = new JFrame("Exit"); 
        if (JOptionPane.showConfirmDialog(frame,"Confirm if you want to exit", "Point Of Sale",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_jbtnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new POS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JButton jbtn0;
    private javax.swing.JButton jbtn1;
    private javax.swing.JButton jbtn2;
    private javax.swing.JButton jbtn3;
    private javax.swing.JButton jbtn4;
    private javax.swing.JButton jbtn5;
    private javax.swing.JButton jbtn6;
    private javax.swing.JButton jbtn7;
    private javax.swing.JButton jbtn8;
    private javax.swing.JButton jbtn9;
    private javax.swing.JButton jbtnAirforce1;
    private javax.swing.JButton jbtnC;
    private javax.swing.JButton jbtnCampus;
    private javax.swing.JButton jbtnChunky;
    private javax.swing.JButton jbtnConverse;
    private javax.swing.JButton jbtnConverseLow;
    private javax.swing.JButton jbtnDot;
    private javax.swing.JButton jbtnDunk;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnGucci;
    private javax.swing.JButton jbtnNb480;
    private javax.swing.JButton jbtnNb530;
    private javax.swing.JButton jbtnOnitsuka;
    private javax.swing.JButton jbtnOxford;
    private javax.swing.JButton jbtnPay;
    private javax.swing.JButton jbtnPrint;
    private javax.swing.JButton jbtnRemove;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnSamba;
    private javax.swing.JButton jbtnTravis;
    private javax.swing.JButton jbtnVans;
    private javax.swing.JButton jbtnWhite;
    private javax.swing.JButton jbtnjm;
    private javax.swing.JButton jbtnplayboy;
    private javax.swing.JButton jbtnpuma;
    private javax.swing.JButton jbtnysl;
    private javax.swing.JButton jbtnzara;
    private javax.swing.JComboBox<String> jcboPayment;
    private javax.swing.JTextField jtxtBarcode;
    private javax.swing.JTextField jtxtChange;
    private javax.swing.JTextField jtxtDisplay;
    private javax.swing.JTextField jtxtSubtotal;
    private javax.swing.JTextField jtxtTax;
    private javax.swing.JTextField jtxtTotal;
    // End of variables declaration//GEN-END:variables
}
